name: E2E Tests

on: push

jobs:
  coverage:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.1
          run_install: |
            - args: [--filter @foleon/web...]

      - name: Start app
        run: |
          pnpm --filter @foleon/web start'
          npx wait-on http://localhost:3000
        env:
          CI: true
          NEXT_PUBLIC_CLIENT_ID: ${{secrets.CYPRESS_PUBLIC_CLIENT_ID}}
          NEXT_PUBLIC_CLIENT_SECRET: ${{secrets.CYPRESS_PUBLIC_CLIENT_SECRET}}

      - name: Run E2E test with Cypress
        run: |
          pnpm --filter @foleon/web cypress:ci
        env:
          CI: true
