name: E2E Tests

on:
  push:
    paths:
      - ./apps/web

jobs:
  coverage:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.1
          run_install: |
            - args: [--filter @foleon/web...]

      - name: Build
        run: |
          pnpm --filter @foleon/web build
        env:
          NEXT_PUBLIC_CLIENT_ID: ${{secrets.CYPRESS_PUBLIC_CLIENT_ID}}
          NEXT_PUBLIC_CLIENT_SECRET: ${{secrets.CYPRESS_PUBLIC_CLIENT_SECRET}}

      - name: Start server app and run tests
        run: |
          pnpm --filter @foleon/web teste2e:ci
        env:
          CI: true
