name: E2E Tests

on:
  workflow_run:
    workflows: ['Unit Tests']
    types:
      - completed

jobs:
  coverage:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - name: Install dependencies
        run: pnpm install

      - name: Run E2E test with Cypress
        uses: cypress-io/github-action@v5
        with:
          build: pnpm --filter @foleon/web build
          start: pnpm --filter @foleon/web start
          wait-on: 'http://localhost:3000'
