name: Unit Tests

on: push

jobs:
  coverage:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: |
          pnpm run test
