name: Tests

on: pull_request

jobs:
  coverage:
    name: Tests coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - name: Install dependencies
        run: pnpm install

      - name: Test coverage
        run: |
          pnpm run test
